metadata:
  description: config for RRFS_NA_3km, grib2, 6hr forecast, grid/orog/sfc_climo OFF
user:
  RUN_ENVIR: community
  MACHINE: wcoss2
  ACCOUNT: RRFS-DEV
platform:
  BUILD_MOD_FN: build_wcoss2_intel
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 3
  EXPT_SUBDIR: test_NA3km_6h
  CCPP_PHYS_SUITE: FV3_GFS_v15_thompson_mynn_lam3km
  DATE_FIRST_CYCL: '20220810'
  DATE_LAST_CYCL: '20220810'
  CYCL_HRS:
    - 00
  FCST_LEN_HRS: 6
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
workflow_switches:
  RUN_TASK_MAKE_GRID: false
  RUN_TASK_MAKE_OROG: false
  RUN_TASK_MAKE_SFC_CLIMO: false
  RUN_TASK_GET_OBS_CCPA: false
  RUN_TASK_GET_OBS_MRMS: false
  RUN_TASK_GET_OBS_NDAS: false
  RUN_TASK_VX_GRIDSTAT: false
  RUN_TASK_VX_POINTSTAT: false
  RUN_TASK_VX_ENSGRID: false
  RUN_TASK_VX_ENSPOINT: false
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: grib2
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  FV3GFS_FILE_FMT_LBCS: grib2
  LBC_SPEC_INTVL_HRS: 6
task_make_grid:
  GRID_DIR:
task_make_orog:
  WTIME_MAKE_OROG: 01:00:00
  OROG_DIR:
task_make_sfc_climo:
  SFC_CLIMO_DIR:
task_make_ics:
  NNODES_MAKE_ICS: 12
  PPN_MAKE_ICS: 4
  OMP_STACKSIZE_MAKE_ICS: 2048m
task_make_lbcs:
  NNODES_MAKE_LBCS: 12
  PPN_MAKE_LBCS: 4
  WTIME_MAKE_LBCS: 01:00:00
task_run_fcst:
  QUILTING: true
  PREDEF_GRID_NAME: RRFS_NA_3km
  PPN_RUN_FCST: 62
  WTIME_RUN_FCST: 02:00:00
  OMP_STACKSIZE_RUN_FCST: 2048m
  WRTCMP_write_groups: 3
  WRTCMP_write_tasks_per_group: 112
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
