metadata:
  description: config for CONUS 25km, netcdf IC/LBCs, 6hr forecast
user:
  RUN_ENVIR: community
  MACHINE: wcoss2
  ACCOUNT: RRFS-DEV
platform:
  BUILD_MOD_FN: build_wcoss2_intel
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 3
  EXPT_SUBDIR: test_netcdf_6h
  CCPP_PHYS_SUITE: FV3_GFS_v16
  DATE_FIRST_CYCL: '2022081000'
  DATE_LAST_CYCL: '2022081000'
  FCST_LEN_HRS: 6
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  COMPILER: intel
workflow_switches:
  RUN_TASK_MAKE_GRID: true
  RUN_TASK_MAKE_OROG: true
  RUN_TASK_MAKE_SFC_CLIMO: true
  RUN_TASK_GET_OBS_CCPA: false
  RUN_TASK_GET_OBS_MRMS: false
  RUN_TASK_GET_OBS_NDAS: false
  RUN_TASK_VX_GRIDSTAT: false
  RUN_TASK_VX_POINTSTAT: false
  RUN_TASK_VX_ENSGRID: false
  RUN_TASK_VX_ENSPOINT: false
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: netcdf
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
  FV3GFS_FILE_FMT_LBCS: netcdf
task_run_fcst:
  WTIME_RUN_FCST: 00:30:00
  QUILTING: true
  PREDEF_GRID_NAME: RRFS_CONUS_25km
  PPN_RUN_FCST: 62
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
