metadata:
  description: This script is to test the restart capability.
user:
  RUN_ENVIR: community
  MACHINE: HERA
  ACCOUNT: naqfc
platform:
  BUILD_MOD_FN: build_hera_intel
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 3
  EXPT_SUBDIR: test_restart
  CCPP_PHYS_SUITE: FV3_GFS_v16
  PREDEF_GRID_NAME: RRFS_CONUS_25km
  DATE_FIRST_CYCL: '2022070100'
  DATE_LAST_CYCL: '2022070100'
  FCST_LEN_HRS: 6
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: false
  DEBUG: false
  COMPILER: intel
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: netcdf
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  FV3GFS_FILE_FMT_LBCS: netcdf
  LBC_SPEC_INTVL_HRS: 3
task_run_fcst:
  RESTART_INTERVAL: 3
  DO_FCST_RESTART: true
